apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-flask-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-flask-app
  template:
    metadata:
      labels:
        app: my-flask-app
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: my-flask-container
          image: public.ecr.aws/f7b0e1m6/chucthien:op
          ports:
            - containerPort: 5000
          imagePullPolicy: Always
