apiVersion: v1
kind: Service
metadata:
  name: my-flask-service
  # namespace: myapp # specify the namespace for the service
spec:
  selector:
    app: my-flask-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP


# apiVersion: v1
# kind: Service
# metadata:
#   name: my-flask-service
#   # namespace: myapp # specify the namespace for the service
# spec:
#   selector:
#     app: my-flask-app
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 5000
#   type: LoadBalancer



