apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter
spec:
  project: default
  sources:
    - chart: karpenter
      repoURL: oci://public.ecr.aws/karpenter/karpenter
      targetRevision: 1.6.0
      helm:
        valueFiles:
          - $values/karpenter/values.yaml
    - repoURL: 'https://github.com/TranChucThien/argocd-example.git'
      targetRevision: HEAD
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
