name: Run Jobs in Parallel and Aggregate Results

on:
  push:
    branches:
      - main

jobs:
  # Job 1: Chạy song song với Job 2 và Job 3
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run Task in Job 1
        run: |
          echo "Job 1 is running"
          sleep 2
          echo "Job 1 is completed"

  # Job 2: Chạy song song với Job 3 và lưu kết quả dưới dạng artifact
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run Task 2
        run: |
          echo "Task 2 is running"
          sleep 3
          echo "Task 2 is completed"
          echo "Task 2 result" > result_task2.txt  # Ghi kết quả vào file
      - name: Upload Task 2 result as artifact
        uses: actions/upload-artifact@v3
        with:
          name: result_task2
          path: result_task2.txt

  # Job 3: Chạy song song với Job 2 và lưu kết quả dưới dạng artifact
  job3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run Task 3
        run: |
          echo "Task 3 is running"
          sleep 4
          echo "Task 3 is completed"
          echo "Task 3 result" > result_task3.txt  # Ghi kết quả vào file
      - name: Upload Task 3 result as artifact
        uses: actions/upload-artifact@v3
        with:
          name: result_task3
          path: result_task3.txt

  # Job 4: Tổng hợp kết quả từ Job 2 và Job 3
  job4:
    needs: [job2, job3]  # Job 4 chỉ chạy sau khi Job 2 và Job 3 hoàn thành
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Download artifacts from Job 2 and Job 3
        uses: actions/download-artifact@v3
        with:
          name: result_task2
      - name: Download Task 3 result artifact
        uses: actions/download-artifact@v3
        with:
          name: result_task3
      - name: Aggregate Results from Job 2 and Job 3
        run: |
          echo "Job 4 is running"
          # Lấy kết quả từ các file đã được tải xuống
          cat result_task2.txt
          cat result_task3.txt
          echo "Job 4 is completed and results are aggregated"
