name: Demo Workflow Dispatch with Selective Job Execution

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment to deploy to'
        required: true
        default: 'staging'
        type: choice
        options:
        - staging
        - production
      region:
        description: 'Select the deployment region'
        required: false
        type: string
        default: 'us-east-1'
      job_to_run:
        description: 'Select the specific job to run (leave empty to run all)'
        required: false
        type: choice
        options:
        - job_one
        - job_two
        - job_three
        - job_four

jobs:
  job_one:
    if: github.event.inputs.job_to_run == '' || github.event.inputs.job_to_run == 'job_one'
    runs-on: ubuntu-latest
    steps:
    - name: Echo One
      run: echo "Job One running in ${{ github.event.inputs.environment }} in region ${{ github.event.inputs.region }}"

  job_two:
    if: github.event.inputs.job_to_run == '' || github.event.inputs.job_to_run == 'job_two'
    runs-on: ubuntu-latest
    needs: job_one
    steps:
    - name: Echo Two
      run: echo "Job Two running after Job One"

  job_three:
    if: github.event.inputs.job_to_run == '' || github.event.inputs.job_to_run == 'job_three'
    runs-on: ubuntu-latest
    needs: job_one
    steps:
    - name: Echo Three
      run: echo "Job Three also running after Job One"

  job_four:
    if: github.event.inputs.job_to_run == '' || github.event.inputs.job_to_run == 'job_four'
    runs-on: ubuntu-latest
    needs: [job_two, job_three]
    steps:
    - name: Echo Four
      run: echo "Job Four running after Job Two and Job Three are complete"
