name: Docker Build

on:
  push:
    tags:
      - 'v*'  # chỉ trigger khi push tag như v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4


      - name: Build & Push Docker Image
        run: |
          ls
          cd argocd-example
          git branch
          TAG=${{ github.ref_name }}  # ví dụ: v1.0.0
          echo $TAG

